name: tochegando_driver
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bottom_picker: ^2.8.0
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.1
  google_sign_in: ^6.2.2
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.0
  googleapis_auth: ^1.6.0
  dropdown_search: ^5.0.6
  file_picker: ^8.1.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  flutter_easyloading: ^3.0.5

  ## O pacote que exige google_api_headers moderno
  flutter_google_places_hoc081098: ^2.0.0

  flutter_html: any
  flutter_local_notifications: ^17.2.3
  flutter_paypal_native: ^2.1.0
  flutter_polyline_points: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_stripe: ^11.2.0
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get: ^4.6.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  map_launcher: ^3.5.0
  path_provider: ^2.1.4
  photo_view: ^0.15.0
  pinput: ^5.0.0
  razorpay_flutter: ^1.3.7
  shared_preferences: ^2.3.2
  firebase_app_check: ^0.3.1+4
  text_scroll: ^0.2.0
  url_launcher: ^6.3.1
  video_compress: ^3.1.3
  video_player: ^2.9.2
  video_thumbnail: ^0.5.3
  google_fonts: ^6.2.1
  location: ^7.0.1
  google_maps_flutter: ^2.9.0
  flutter_osm_plugin: ^1.3.5
  provider: ^6.1.2
  in_app_review: ^2.0.9

  ## CORRIGIDO
  google_api_headers: ^4.2.5

dependency_overrides:
  webview_flutter: ^4.10.0
  syncfusion_flutter_pdfviewer: any
  http: ^1.2.2
  uuid: ^4.5.1
  js: ^0.7.1
  google_api_headers: ^4.2.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/file/
    - assets/icons/
    - assets/flags/
    - assets/

  fonts:
    - family: Switzer-Black
      fonts:
        - asset: assets/fonts/Switzer-Black.otf

    - family: Switzer-Bold
      fonts:
        - asset: assets/fonts/Switzer-Bold.otf

    - family: Switzer-Extrabold
      fonts:
        - asset: assets/fonts/Switzer-Extrabold.otf

    - family: Switzer-Extralight
      fonts:
        - asset: assets/fonts/Switzer-Extralight.otf

    - family: Switzer-Italic
      fonts:
        - asset: assets/fonts/Switzer-Italic.otf

    - family: Switzer-Medium
      fonts:
        - asset: assets/fonts/Switzer-Medium.otf

    - family: Switzer-Regular
      fonts:
        - asset: assets/fonts/Switzer-Regular.otf

    - family: Switzer-Semibold
      fonts:
        - asset: assets/fonts/Switzer-Semibold.otf

    - family: Switzer-Thin
      fonts:
        - asset: assets/fonts/Switzer-Thin.otf
